(() => {
 const $=id=>document.getElementById(id),points={start:{lat:43.0687,lng:141.3508,name:'札幌駅北口'},goal:null};
 let map,layer,markers={},target='goal',route=null,revision=0,requestId=0,searchBusy=false,config;
 const cache=new Map(),routeCache=new Map();
 const getConfig=()=>config||(config=fetch('./map-config.json').then(r=>{if(!r.ok)throw Error('地図の設定を読み込めませんでした。');return r.json();}).catch(e=>{config=null;throw e;}));
 const format=m=>Math.floor(m/60)+'時間'+(m%60?m%60+'分':'');
 function status(s){$('mapStatus').textContent=s;}
 function invalidate(){revision++;route=null;$('mapApply').hidden=true;$('mapInsuranceField').hidden=true;$('mapRouteSummary').hidden=true;if(layer){map.removeLayer(layer);layer=null;}status('場所を選んだら「往復ルートを計算」を押してください。');}
 function select(key){target=key;for(const k of ['start','goal'])$('map'+(k==='start'?'Start':'Goal')+'Tab').setAttribute('aria-pressed',k===key);$('mapHint').textContent=(key==='start'?'出発地':'目的地')+'にしたい場所を地図でタップしてください。';}
 function showMarkers(){for(const key of ['start','goal']){const p=points[key];if(markers[key])map.removeLayer(markers[key]);if(!p)continue;const icon=L.divIcon({className:'map-pin '+key,html:key==='start'?'出':'着',iconSize:[28,28],iconAnchor:[14,14]});markers[key]=L.marker([p.lat,p.lng],{icon,draggable:true}).addTo(map).bindTooltip(p.name);markers[key].on('dragend',e=>{const ll=e.target.getLatLng();setPoint(key,{lat:ll.lat,lng:ll.lng,name:'地図で選んだ地点'},false);});}}
 function setPoint(key,p,pan=true){points[key]=p;if(key==='goal')suggestStay();$('map'+(key==='start'?'Start':'Goal')+'Label').textContent=p.name;invalidate();if(map){showMarkers();if(pan)map.setView([p.lat,p.lng],13);}if(key==='start')select('goal');}
 async function init(){if(map){map.invalidateSize();return;}try{const c=await getConfig();if(!window.L)throw Error('地図を読み込めませんでした。再読み込みしてください。');map=L.map('tripMap',{scrollWheelZoom:false}).setView([43.065,141.35],12);L.tileLayer(c.tiles,{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);map.on('click',e=>setPoint(target,{lat:e.latlng.lat,lng:e.latlng.lng,name:'地図で選んだ地点'},false));showMarkers();select('goal');}catch(e){status(e.message);}}
 async function fetchJson(url){const response=await fetch(url,{signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('地図サービスに接続できませんでした。少し待って再試行してください。');return response.json();}
 function suggestStay(){if(!$('mapStayAuto').checked){$('mapStayReason').textContent='手動設定を優先しています。目的地を変えても滞在時間はそのままです。';return;}const hint=estimateStay(points.goal);$('mapStay').value=String(hint.minutes/60);$('mapStayReason').textContent=hint.reason+'（滞在の目安 '+format(hint.minutes)+'）。予定に合わせて調整してください。';if(window.syncConditionControls)window.syncConditionControls();}
 function liveExtras(){render();if(route)apply(false);}
 function extras(){const stay=Number($('mapStay').value),buffer=Number($('mapBuffer').value);if($('mapStay').value===''||$('mapBuffer').value===''||!Number.isFinite(stay)||!Number.isFinite(buffer)||stay<0||buffer<0||stay>168||buffer>600)throw Error('滞在時間と余裕時間を正しく入力してください。');return {stay:Math.ceil(stay*60),buffer:Math.ceil(buffer)};}
 function totals(){const x=extras(),driving=route.legs.reduce((sum,leg)=>sum+Math.ceil(leg.duration/60),0),total=driving+x.stay+x.buffer;if(total>10080)throw Error('利用時間が7日を超えています。滞在時間を調整してください。');return {...x,total,km:Math.ceil(route.distance/100)/10,driving};}
 function render(){if(!route)return;try{const t=totals();$('mapRouteSummary').innerHTML='<div class="map-metrics"><div class="map-metric"><span>往復の走行距離</span><strong>'+t.km+' km</strong></div><div class="map-metric"><span>往復の運転時間</span><strong>約'+format(t.driving)+'</strong></div></div><div class="map-breakdown">往路 '+format(Math.ceil(route.legs[0].duration/60))+' / 復路 '+format(Math.ceil(route.legs[1].duration/60))+'</div><div class="map-time-total">車を借りる時間 <strong>'+format(t.total)+'</strong><div class="map-breakdown">運転 '+format(t.driving)+' ＋ 滞在 '+format(t.stay)+' ＋ 余裕 '+t.buffer+'分</div></div>';$('mapRouteSummary').hidden=false;$('mapApply').hidden=false;$('mapInsuranceField').hidden=false;$('mapInsurance').checked=$('insurance').checked;status('この往復距離・利用時間で料金を計算します。補償を選んで、下のボタンを押してください。');}catch(e){$('mapApply').hidden=true;$('mapInsuranceField').hidden=true;status(e.message);}}
 async function calculate(){if(!points.goal){status('目的地を選んでください。');return;}const ver=revision,id=++requestId;try{extras();$('mapCalculate').disabled=true;status('往路・復路の道路ルートを計算しています…');const c=await getConfig(),a=points.start,b=points.goal,coords=a.lng+','+a.lat+';'+b.lng+','+b.lat+';'+a.lng+','+a.lat;let data=routeCache.get(coords);if(!data){data=await fetchJson(c.route+coords+'?overview=simplified&geometries=geojson&steps=false');if(data.code!=='Ok'||!data.routes?.length)throw Error('往復できる道路ルートが見つかりませんでした。道路沿いの地点を選んでください。');routeCache.set(coords,data);}if(ver!==revision||id!==requestId)return;const r=data.routes[0];if(!Number.isFinite(r.distance)||!Number.isFinite(r.duration)||r.legs?.length!==2)throw Error('経路の情報を取得できませんでした。');if(data.waypoints?.some(p=>p.distance>1500))throw Error('選択地点から道路まで離れています。駐車場や道路に近い地点を選んでください。');route=r;if(map){if(layer)map.removeLayer(layer);layer=L.geoJSON(r.geometry,{style:{color:'#406995',weight:5,opacity:.85}}).addTo(map);map.fitBounds(layer.getBounds(),{padding:[25,25]});}render();apply(false);}catch(e){if(ver===revision){route=null;$('mapApply').hidden=true;$('mapInsuranceField').hidden=true;$('mapRouteSummary').hidden=true;status(e.name==='TimeoutError'?'通信がタイムアウトしました。もう一度お試しください。':e.message);}}finally{if(id===requestId)$('mapCalculate').disabled=false;}}
 function apply(scroll=true){if(!route)return;try{const t=totals();if(mode==='date'){const start=dateMinute($('startDate').value,$('startClock').value),end=start+t.total;$('endDate').value=new Date(end*60000).toISOString().slice(0,10);$('endClock').value=hhmm(end%1440);}else{$('hours').value=Math.floor(t.total/60);$('minutes').value=t.total%60;}$('distance').value=t.km;update();status('往復 '+t.km+'km・利用 '+format(t.total)+' を反映しました。下の料金が更新されています。');if(scroll)showResults();}catch(e){status(e.message);}}
 async function search(){const q=$('mapSearchText').value.trim();if(!q||searchBusy)return;searchBusy=true;$('mapSearchButton').disabled=true;const searchTarget=target;try{status('場所を検索しています…');const c=await getConfig();let data=cache.get(q);if(!data){const center=map?map.getCenter():points.start;data=await fetchJson(c.search+'?q='+encodeURIComponent(q)+'&limit=5&lat='+center.lat+'&lon='+center.lng);cache.set(q,data);}const list=$('mapSearchResults');list.replaceChildren();for(const f of data.features||[]){const [lng,lat]=f.geometry.coordinates,p=f.properties,name=p.name||[p.street,p.housenumber].filter(Boolean).join(' ')||'検索した地点';const button=document.createElement('button');button.className='map-search-result';button.textContent=[name,p.city,p.state,p.country].filter(Boolean).join(' · ');button.onclick=()=>{setPoint(searchTarget,{lat,lng,name,kind:p.osm_value||p.type||''});list.replaceChildren();status('場所を設定しました。');};list.appendChild(button);}status(data.features?.length?'候補から'+(searchTarget==='start'?'出発地':'目的地')+'を選んでください。':'見つかりませんでした。市町村名を足すか、地図で選んでください。');}catch(e){status('検索できませんでした。地図をタップして選択できます。');}finally{searchBusy=false;$('mapSearchButton').disabled=false;}}
 $('mapPlanner').addEventListener('toggle',()=>{if($('mapPlanner').open)init();});$('mapStartTab').onclick=()=>select('start');$('mapGoalTab').onclick=()=>select('goal');$('mapSearchButton').onclick=search;$('mapSearchText').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search();}});
 $('mapInsurance').addEventListener('change',()=>{$('insurance').checked=$('mapInsurance').checked;update();});$('insurance').addEventListener('change',()=>{$('mapInsurance').checked=$('insurance').checked;});$('mapCalculate').onclick=calculate;$('mapApply').onclick=()=>apply(true);$('mapStay').addEventListener('input',()=>{$('mapStayAuto').checked=false;$('mapStayReason').textContent='手動で調整中。目的地を変えてもこの滞在時間を優先します。';liveExtras();});$('mapBuffer').addEventListener('input',liveExtras);$('mapStayAuto').addEventListener('change',()=>{suggestStay();liveExtras();});
 $('mapSapporo').onclick=()=>setPoint('start',{lat:43.0687,lng:141.3508,name:'札幌駅北口'});$('mapOtaru').onclick=()=>setPoint('goal',{lat:43.1977,lng:140.9936,name:'小樽駅',kind:'sightseeing'});$('mapChitose').onclick=()=>setPoint('goal',{lat:42.7875,lng:141.6809,name:'新千歳空港'});
 $('mapLocate').onclick=()=>{if(!navigator.geolocation){status('この端末では現在地を取得できません。');return;}status('現在地を確認しています…');navigator.geolocation.getCurrentPosition(p=>{setPoint('start',{lat:p.coords.latitude,lng:p.coords.longitude,name:'現在地'});status('現在地を出発地に設定しました。');},()=>status('現在地を取得できませんでした。地図で出発地を選んでください。'),{enableHighAccuracy:false,timeout:15000,maximumAge:60000});};
})();
